---
apiVersion: v1
kind: Pod
metadata:
  name: go-named-pipes
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}

  containers:
    - name: pipes-client
      image: named-pipes-poc
      imagePullPolicy: Never
      volumeMounts:
        - name: shared-volume
          mountPath: /tmp
    - name: pipes-server
      image: named-pipes-poc
      imagePullPolicy: Never
      volumeMounts:
        - name: shared-volume
          mountPath: /tmp
      command: ["./mongodb-linux-aarch64-ubuntu2004-6.2.0/bin/mongod"]
      args: ["--dbpath", "mongodb-data", "--logpath", "mongod.log", "--bind_ip", "localhost", "--port", "27017", "--setParameter", "enableComputeMode=true"]
