---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-client-server
spec:
  containers:
    - name: reader
      image: go-reader
      imagePullPolicy: Never
    - name: writer
      image: go-writer
      imagePullPolicy: Never
