---
apiVersion: v1
kind: Pod
metadata:
  name: go-client-server
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}

  containers:
    - name: pipes-client
      image: pipes-client
      imagePullPolicy: Never
      volumeMounts:
        - name: shared-volume
          mountPath: /tmp
    - name: pipes-server
      image: pipes-server
      imagePullPolicy: Never
      volumeMounts:
        - name: shared-volume
          mountPath: /tmp
